// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.iOS.ViewControllers;
using Electrolux.ShopFloor.Mvvm.ViewModels.EditingAreas;

using Foundation;
using UIKit;
using Electrolux.ShopFloor.Mvvm.ViewModels;
using Electrolux.ShopFloor.Middleware.Manager;
using GalaSoft.MvvmLight.Helpers;
using CoreGraphics;
using System.Diagnostics;

namespace Electrolux.ShopFloor.iOS.ViewControllers
{
	[Register("AreaBaseViewController")]
	public class DetailBaseViewController<T> : BaseViewController<ReportEditorViewModel> where T : AreaViewModelBase
	{

		public DetailBaseViewController(IntPtr handle) : base(handle)
		{
		}

		public T AreaViewModel
		{
			get { return ViewModel.ActiveArea as T; }
		}
	}
}
