// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Electrolux.ShopFloor.iOS.ViewControllers;
using Electrolux.ShopFloor.Middleware.Manager;
using Electrolux.ShopFloor.Mvvm.ViewModels.EditingAreas;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class CommentViewController : DetailBaseViewController<UserCommentsViewModel>
	{
		public CommentViewController (IntPtr handle) : base (handle)
		{
		}

		public override void Translations()
		{
			this.commentLabel.Text = TranslatorManager.GetInstance().GetString("Comments");
		}

		public override void RegisterBindingsLocal()
		{
			base.RegisterBindingsLocal();

			if (this.AreaViewModel == null)
				return;

			KeepBindingInMemoryLocal(new Binding<string, string>(
				this.AreaViewModel,
				() => this.AreaViewModel.Comment,
				this,
				() => this.commentTextView.Text,
				BindingMode.TwoWay));
		}
	}
}
