// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class AppNavigationController : UINavigationController
	{
		public AppNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
