// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.iOS;
using Electrolux.ShopFloor.Mvvm.ViewModels.EditingAreas;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS.ViewControllers
{
	public partial class GeneralInformationDatesViewController : DetailBaseViewController<GeneralInfoViewModel>
	{
		public GeneralInformationDatesViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ConfigureArea()
		{
			base.ConfigureArea();

			this.tableView.DataSource = new BaseTableViewDataSource<DateUnit>(AreaViewModel.Dates, this.tableView, "GeneralInformationDatesViewCell");
			this.tableView.Delegate = new BaseTableViewDelegate((UITableViewCell obj) =>
			{
			});
		}
	}
}
