// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class TimePickerViewController : UIViewController
	{
		public TimePickerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
