// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;


namespace Electrolux.ShopFloor.iOS
{
	public partial class PosmActivitiesTableViewCell : UITableViewCell
	{

		public PosmActivityUnit Item { get; set; }

		public UILabel ModelCategoryLabel { get { return modelCategoryLabel; } }
		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel PosmActivityLabel { get { return posmActivityLabel; } }
		public UILabel PosmCampaignLabel { get { return posmCampaignLabel; } }
		public UILabel PosmMaterialLabel { get { return posmMaterialLabel; } }

		public PosmActivitiesTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
