// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Electrolux.ShopFloor.Middleware.Manager;

namespace Electrolux.ShopFloor.iOS
{
	public partial class CollectionReusableviewRowHeader : UICollectionReusableView
	{
		public UILabel CategoryLabel {
			get {
				return categoryLabel;
			}
		}

		public UILabel QtyLabel
		{
			get
			{
				return qtyLabel;
			}
		}
		public UILabel QtyOnStockLabel
		{
			get
			{
				return qtyOnStockLabel;
			}
		}
		public UILabel QtyPOSLabel
		{
			get
			{
				return qtyPOSLabel;
			}
		}
		public UILabel QtyShelfLabel
		{
			get
			{
				return qtyShelfLabel;
			}
		}
		public CollectionReusableviewRowHeader (IntPtr handle) : base (handle)
		{
		}

		public void Translations()
		{
			this.QtyLabel.Text = TranslatorManager.GetInstance().GetString("Qty");
			this.QtyOnStockLabel.Text = TranslatorManager.GetInstance().GetString("Quantity On Stock");
			this.QtyPOSLabel.Text = TranslatorManager.GetInstance().GetString("Quantity With POS Material");
			this.QtyShelfLabel.Text = TranslatorManager.GetInstance().GetString("Quantity On Display");
		}

	}
}
