// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class CollectionReusableviewColumnHeader : UICollectionReusableView
	{
		public UILabel BrandLabel
		{
			get {
				return brandLabel;
			}
		}
		public CollectionReusableviewColumnHeader (IntPtr handle) : base (handle)
		{
		}
	}
}
