// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Electrolux.ShopFloor.Mvvm.ViewModels.EditingAreas;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FSCompetitorByBrandProductGroupsCell : UITableViewCell
	{
		public List<Binding> Bindings { get; set; }

		public Action<UIView> checkProductGroupAction { get; set; }
		public UILabel ProductGroupLabel { get { return productGroupLabel; } }
		public UIButton CheckProductGroupButton { get { return checkProductGroupButton; } }
		public UIImageView IsSelectedImageView { get { return isSelectedImageView; } }

		public FSCompetitorByBrandProductGroupsCell (IntPtr handle) : base (handle)
		{
		}

		partial void checkProductGroupButtonAction(NSObject sender)
		{
			this.checkProductGroupAction(sender as UIView);
		}

		public void BindCell(CompetitorsFloorSpace2020ViewModel viewModel, NSIndexPath indexPath)
		{
			if (this.Bindings != null)
			{
				foreach (Binding binding in this.Bindings)
				{
					binding.Detach();
				}
				this.Bindings.Clear();
			}
			else
			{
				this.Bindings = new List<Binding>();
			}

			this.ProductGroupLabel.Text = viewModel.Categories[indexPath.Row].Text;
			this.checkProductGroupAction = (UIView sender) =>
			{
				viewModel.Categories[indexPath.Row].IsSelected = !viewModel.Categories[indexPath.Row].IsSelected;
				viewModel.SetFilterCategoryLabel();
			};

			this.Bindings.Add(new Binding<bool, UIImage>(viewModel.Categories[indexPath.Row], () => viewModel.Categories[indexPath.Row].IsSelected, this, () => this.IsSelectedImageView.Image, BindingMode.OneWay)
								  .ConvertSourceToTarget((bool arg) =>
								  {
									  return arg ? UIImage.FromBundle("select-icon") : new UIImage();
								  })
								 );

		}
	}
}
