// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class MainCollectionCell : UICollectionViewCell
	{
		public MainCollectionCell (IntPtr handle) : base (handle)
		{
		}

		public List<Binding> Bindings { get; set; }

		public Action<UIView> qtyMinusButtonAction { get; set; }
		public Action<UIView> qtyPlusButtonAction { get; set; }
		public Action<UIView> qtyStockMinusButtonAction { get; set; }
		public Action<UIView> qtyStockPlusButtonAction { get; set; }
		public Action<UIView> qtyPOSMinusButtonAction { get; set; }
		public Action<UIView> qtyPOSPlusButtonAction { get; set; }
		public Action<UIView> qtyDisplayMinusButtonAction { get; set; }
		public Action<UIView> qtyDisplayPlusButtonAction { get; set; }

		public UILabel QtyLabel { get { return qtyLabel; } }
		public UILabel QtyOnStockLabel { get { return qtyOnStockLabel; } }
		public UILabel QtyPOSLabel { get { return qtyPOSLabel; } }
		public UILabel QtyOnDisplayLabel { get { return qtyOnDisplayLabel; } }

		partial void qtyMinusAction(NSObject sender)
		{
			this.qtyMinusButtonAction(sender as UIView);
		}

		partial void qtyPlusAction(Foundation.NSObject sender)
		{
			this.qtyPlusButtonAction(sender as UIView);
		}

		partial void qtyStockMinusAction(NSObject sender)
		{
			this.qtyStockMinusButtonAction(sender as UIView);
		}

		partial void qtyStockPlusAction(Foundation.NSObject sender)
		{
			this.qtyStockPlusButtonAction(sender as UIView);
		}

		partial void qtyPOSMinusAction(NSObject sender)
		{
			this.qtyPOSMinusButtonAction(sender as UIView);
		}

		partial void qtyPOSPlusAction(Foundation.NSObject sender)
		{
			this.qtyPOSPlusButtonAction(sender as UIView);
		}

		partial void qtyDisplayMinusAction(NSObject sender)
		{
			this.qtyDisplayMinusButtonAction(sender as UIView);
		}

		partial void qtyDisplayPlusAction(Foundation.NSObject sender)
		{
			this.qtyDisplayPlusButtonAction(sender as UIView);
		}
	}
}
