// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ProductFeedbackTableViewCell : UITableViewCell
	{
		public ProductFeedbackUnit Item { get; set; }

		public UILabel ModelCategoryLabel { get { return modelCategoryLabel; } }
		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel DescriptionLabel { get { return descriptionLabel; } }

		public ProductFeedbackTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
