// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class AnalyticsPreviousReportDataRowCell : UITableViewCell
	{
		public UILabel ProductGroupLabel { get { return productGroupLabel; } }
		public UILabel StarProductLabel { get { return starProductLabel; } }
		public UILabel TotalElectroluxLabel { get { return totalElectroluxLabel; } }
		public UILabel TotalOtherLabel { get { return totalOtherLabel; } }
		public UILabel TotalOverallLabel { get { return totalOverallLabel; } }
        public UILabel PercentOverTotalLabel { get { return percentOverTotalLabel; } }

        public AnalyticsPreviousReportDataRowCell (IntPtr handle) : base (handle)
		{
		}
	}
}
