// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class KitchenPreviousReportDataRowCell : UITableViewCell
	{
		public UILabel KitchenNameLabel { get { return kitchenNameLabel; } }
		public UILabel TotalElectroluxLabel { get { return totalElectroluxLabel; } }
		public UILabel TotalOtherLabel { get { return totalOtherLabel; } }
		public UILabel TotalOverallLabel { get { return totalOverallLabel; } }

		public KitchenPreviousReportDataRowCell (IntPtr handle) : base (handle)
		{
		}
	}
}
