// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ModelVariationsCell : UITableViewCell
	{
		public UILabel BrandLabel { get { return brandLabel;} }
		public UILabel ModelLabel { get { return modelLabel; } }
		public UILabel ProductGroupLabel { get { return productGroupLabel; } }
		public UILabel StarProductLabel { get { return starProductLabel; } }
		public UILabel StatusLabel { get { return statusLabel; } }

		public ModelVariationsCell (IntPtr handle) : base (handle)
		{
		}
	}
}
