// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Electrolux.ShopFloor.Mvvm.ViewModels;
using GalaSoft.MvvmLight.Helpers;
using Electrolux.ShopFloor.Middleware.Model;
using System.Collections.Generic;
using System.Diagnostics;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ReportsViewCell : UITableViewCell
	{
		public Action<UIView> DeleteButtonAction { get; set; }
		public Action<UIView> EditButtonAction { get; set; }
		public Action<UIView> UploadButtonAction { get; set; }
		public Action<UIView> ViewButtonAction { get; set; }
		public Action<UIView> ViewUploadErrorButtonAction { get; set; }

		public UILabel DateLabel { get { return this.dateLabel; } }
		public UIButton DeleteButton { get { return this.deleteButton; } }
		public UIButton EditButton { get { return this.editButton; } }
		public UILabel StoreLabel { get { return this.storeLabel; } }
		public UIButton UploadReportButton { get { return this.uploadReportButton; } }
		public UIButton ViewButton { get { return this.viewButton; } }
		public UIButton ViewUploadErrorButton { get { return this.viewUploadErrorButton; } }
        public UILabel BusinessSectorLabel { get { return this.businessSectorLabel; } }

		public ReportsViewCell(IntPtr handle) : base(handle)
		{
		}

		partial void deleteButtonAction(NSObject sender)
		{
			this.DeleteButtonAction(sender as UIView);
		}

		partial void editButtonAction(NSObject sender)
		{
			this.EditButtonAction(sender as UIView);
		}

		partial void uploadButtonAction(NSObject sender)
		{
			this.UploadButtonAction(sender as UIView);
		}

		partial void viewButtonAction(NSObject sender)
		{
			this.ViewButtonAction(sender as UIView);
		}

		partial void viewUploadErrorButtonAction(NSObject sender)
		{
			this.ViewUploadErrorButtonAction(sender as UIView);
		}

		public void BindCell(ReportUnit item)
		{
		}

	}
}
