// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ReportEditorViewCell : UITableViewCell, ICellBinding<MenuUnit>
	{
		public ReportEditorViewCell (IntPtr handle) : base (handle)
		{
		}

		public MenuUnit Item { get; set; }

		public void BindCell(MenuUnit item)
		{
			this.Item = item;

			this.moduleNameLabel.Text = item.Name;

			if (item.IsCompleted)
			{
				this.moduleCompletedImageView.Image = UIImage.FromBundle("select-icon");
			}
			else if (item.IsMandatory)
			{
				this.moduleCompletedImageView.Image = UIImage.FromBundle("asterisk-icon");
			}
			else {
				this.moduleCompletedImageView.Image = null;
			}

			if (item.IsEnabled)
			{
				this.EnableCell();
			}
			else {
				this.DisableCell();
			}
		}

		private void EnableCell()
		{
			this.UserInteractionEnabled = true;
			this.TextLabel.Alpha = 1.0f;
		}

		private void DisableCell()
		{
			this.UserInteractionEnabled = false;
			this.TextLabel.Alpha = 0.439216f; // (1 - alpha) * 255 = 143
		}
	}
}
