// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class SelloutTableViewCell : UITableViewCell
	{
		public SoldProductUnit Item { get; set; }
		public UILabel InEvidenceLabel { get { return inEvidenceLabel; } }
		public UILabel InStockLabel { get { return inStockLabel; } }
		public UILabel ModelProductSetLabel { get { return modelProductSetLabel; } }
		public UILabel PncLabel { get { return pncLabel; } }
		public UILabel PriceLabel { get { return priceLabel; } }
		public UILabel QuantityLabel { get { return quantityLabel; } }

		public SelloutTableViewCell(IntPtr handle) : base(handle)
		{
		}
	}
}
