// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class KitchenItemsTableViewCell : UITableViewCell
	{
		public List<Binding> Bindings { get; set; }

		public UILabel ModelLabel { get { return modelLabel; } }
		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel CategoryLabel { get { return categoryLabel; } }
		public UILabel QtyLabel { get { return qtyLabel; } }
		public UILabel PriceLabel { get { return priceLabel; } }
		public UILabel PreferredModelIndicatorLabel { get { return preferredModelIndicatorLabel; } }
		public UILabel QtySpecialLabel { get { return qtySpecialLabel; } } 
		public UILabel QtyPromoLabel { get { return qtyPromoLabel; } } 

		public KitchenItemsTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
