// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ElectroluxActivitiesTableViewCell : UITableViewCell
	{

		public ElectroluxActivityUnit Item { get; set; }

		public UILabel ActivityLabel { get { return activityLabel; } }
		public UILabel ActivityReasonLabel { get { return activityReasonLabel; } }
		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel DescriptionLabel { get { return descriptionLabel; } }
		public UILabel ModelCategoryLabel { get { return modelCategoryLabel; } }
		public UILabel TimeSpentlabel { get { return timeSpentlabel; } }

		public ElectroluxActivitiesTableViewCell(IntPtr handle) : base(handle)
		{
		}
	}
}
