// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class CommentsTableViewCell : UITableViewCell
	{
		public UIKit.UILabel CommentLabel { get { return commentLabel; } }

		public CommentsTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
