// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FullOverviewFloorspaceElectroluxTableViewCell : UITableViewCell
	{
		public UILabel BrandLabel { get { return brandLabel;} }
		public UILabel KitchenLabel { get { return kitchenLabel; } }
		public UILabel ModelLabel { get { return modelLabel; } }
		public UILabel PriceLabel { get { return priceLabel; } }
		public UILabel QtyOnDisplayLabel { get { return qtyOnDisplayLabel; } }
		public UILabel QtySpecialPlacementLabel { get { return qtySpecialPlacementLabel; } }
		public UILabel QtyWithPOSMaterialLabel { get { return qtyWithPOSMaterialLabel; } }

		public FullOverviewFloorspaceElectroluxTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
