// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FullOverviewFloorspaceCompetitorsTableViewCell : UITableViewCell
	{
		public UIKit.UILabel ModelLabel { get { return modelLabel; } }
		public UIKit.UILabel BrandLabel { get { return brandLabel; } }
		public UIKit.UILabel PriceLabel { get { return priceLabel; } }
		public UIKit.UILabel QtyOnDisplayLabel { get { return qtyOnDisplayLabel; } }
		public UIKit.UILabel QtySpecialPlacementLabel { get { return qtySpecialPlacementLabel; } }
		public UIKit.UILabel QtyWithPOSMaterialLabel { get { return qtyWithPOSMaterialLabel; } }
		public UIKit.UILabel KitchenLabel { get { return kitchenLabel; } }
		public UIKit.UILabel ProductGroupLabel { get { return productGroupLabel; } }
		public UIKit.UILabel QtyOnStockLabel { get { return qtyOnStockLabel; } }

		public FullOverviewFloorspaceCompetitorsTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
