// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class ShopInformationTableViewCell : UITableViewCell
	{
		public UILabel CustomerContactedLabel { get { return customerContactedLabel; } }
		public UILabel CustomerPurchasedLabel { get { return customerPurchasedLabel; } }
		public UILabel DailyTrafficLabel { get { return dailyTrafficLabel; } }
		public UILabel WeatherLabel { get { return weatherLabel; } }

		public ShopInformationTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
