// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class TrainingTableViewCell : UITableViewCell
	{
		public UILabel DescriptionLabel { get { return descriptionLabel;} }
		public UILabel MainFocusLabel { get { return mainFocusLabel; } }
		public UILabel NumberOfParticipantsLabel { get { return numberOfParticipantsLabel; } }
		public UILabel TimeSpentLabel { get { return timeSpentLabel; } }
		public UILabel TrainingAudienceLabel { get { return trainingAudienceLabel; } }
		public UILabel TrainingMethodLabel { get { return trainingMethodLabel; } }

		public TrainingTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
