// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Electrolux.ShopFloor.iOS.ViewControllers;
using Electrolux.ShopFloor.Middleware.Manager;
using Electrolux.ShopFloor.Mvvm.ViewModels;
using Electrolux.ShopFloor.Mvvm.ViewModels.EditingAreas;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class CompetitorsActivitiesViewController : ListBaseViewController<CompetitorsActivitiesViewModel, CompetitorActivityUnit>
	{
		protected override string CellName
		{
			get { return "CompetitorsActivitiesTableViewCell"; }
		}

		public override void Translations()
		{
			this.modelHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Model/Category");
			this.brandHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Brand");
			this.timeSpentHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Time Spent");
			this.competitorsActivityHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Competitors Activities");
			this.reasonHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Reason");
			this.descriptionHeaderLabel.Text = TranslatorManager.GetInstance().GetString("Description");
		}

		public override void BindTaskCell(UITableViewCell cell, CompetitorActivityUnit item, NSIndexPath path)
		{
			base.BindTaskCell(cell, item, path);

			CompetitorsActivitiesTableViewCell listCell = cell as CompetitorsActivitiesTableViewCell;

			listCell.ModelLabel.Text = item.ModelText;
			listCell.BrandLabel.Text = item.Brand.Text;
			listCell.CompetitorsActivityLabel.Text = item.Activity.Text;
			listCell.ReasonLabel.Text = item.Reason.Text;
			listCell.TimeSpentLabel.Text = item.TimeSpent.Text;
			listCell.DescriptionLabel.Text = item.Description;
		}

		#region .ctor
		public CompetitorsActivitiesViewController(IntPtr handle) : base(handle)
		{
		}
		#endregion
	}
}
