// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Mvvm.ViewModels.Units;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FloorspaceCompetitorsTableViewCell : UITableViewCell
	{
		public FloorSpaceCompetitorUnit Item { get; set; }
		public UILabel ModelLabel { get { return modelLabel; } }
		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel QtyOnDisplayLabel { get { return qtyOnDisplayLabel; } }
		public UILabel CategoryLabel { get { return categoryLabel; } }
		public UILabel OldEnergyClassLabel { get { return oldEnergyClassLabel; } }
		public UILabel PriceLabel { get { return priceLabel; } }
		public UILabel UpdateEnergyClassLabel { get { return updateEnergyClassLabel; } }

		public FloorspaceCompetitorsTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
