// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using GalaSoft.MvvmLight.Helpers;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FloorspaceProductGroupBrandsTableViewCell : UITableViewCell
	{
		public List<Binding> bindings = new List<Binding>();

		public Action<UIView> QtyPlusAction { get; set; }
		public Action<UIView> QtyMinusAction { get; set; }
		public Action<UIView> QtyPOSPlusAction { get; set; }
		public Action<UIView> QtyPOSMinusAction { get; set; }
		public Action<UIView> QtySpecialPlusAction { get; set; }
		public Action<UIView> QtySpecialMinusAction { get; set; }
		public Action<UIView> QtyPromoPlusAction { get; set; }
		public Action<UIView> QtyPromoMinusAction { get; set; }

		public UILabel BrandLabel { get { return brandLabel; } }
		public UILabel QtyLabel { get { return qtyLabel; } }
		public UILabel QtyPromoLabel { get { return qtyPromoLabel; } }
		public UILabel QtyPOSLabel { get { return qtyPOSLabel; } }
		public UILabel QtySpecialLabel { get { return qtySpecialLabel; } }

		public FloorspaceProductGroupBrandsTableViewCell (IntPtr handle) : base (handle)
		{
		}

		partial void qtyMinusAction(NSObject sender)
		{
			this.QtyMinusAction(sender as UIView);
		}

		partial void qtyPlusAction(NSObject sender)
		{
			this.QtyPlusAction(sender as UIView);
		}

		partial void qtyPOSMinusAction(NSObject sender)
		{
			this.QtyPOSMinusAction(sender as UIView);
		}

		partial void qtyPOSPlusAction(NSObject sender)
		{
			this.QtyPOSPlusAction(sender as UIView);
		}

		partial void qtyPromoMinusAction(NSObject sender)
		{
			this.QtyPromoMinusAction(sender as UIView);
		}

		partial void qtyPromoPlusAction(NSObject sender)
		{
			this.QtyPromoPlusAction(sender as UIView);
		}

		partial void qtySpecialMinusAction(NSObject sender)
		{
			this.QtySpecialMinusAction(sender as UIView);
		}

		partial void qtySpecialPlusAction(NSObject sender)
		{
			this.QtySpecialPlusAction(sender as UIView);
		}
	}
}
