// This file has been autogenerated from a class added in the UI designer.

using System;
using Electrolux.ShopFloor.Middleware.Manager;
using Electrolux.ShopFloor.Middleware.Model.UI;
using Foundation;
using UIKit;

namespace Electrolux.ShopFloor.iOS
{
	public partial class FSElectroluxModelSearchViewCell : UITableViewCell, ICellBinding<ModelModel>
	{
		public ModelModel Item { get; set; }
		public FSElectroluxModelSearchViewCell (IntPtr handle) : base (handle)
		{
		}
		public void BindCell(ModelModel item)
		{
			this.Item = item;
			this.TextLabel.Text = item.ModelName;
			this.DetailTextLabel.Text = TranslatorManager.GetInstance().GetString(item.ModelTypeResource);
		}

	}
}
